# Generated by Django 5.2.11 on 2026-02-21 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('ip_address', models.GenericIPAddressField()),
                ('os_type', models.CharField(choices=[('WINDOWS', 'Windows'), ('LINUX', 'Linux'), ('MAC', 'Mac')], default='WINDOWS', max_length=10)),
                ('monitoring_enabled', models.BooleanField(default=True)),
                ('risk_profile', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('api_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_users', models.ManyToManyField(blank=True, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
