# Generated by ChatGPT on 2026-02-24
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("inapp_notifications", models.BooleanField(default=True)),
                ("email_notifications", models.BooleanField(default=True)),
                ("notify_on_medium", models.BooleanField(default=False)),
                ("notify_on_high", models.BooleanField(default=True)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("compact_sidebar", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("default_device", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="devices.device")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="preference", to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
